# Generated by Django 4.0.3 on 2022-03-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.TextField(default='Ipsum Lorem'),
        ),
        migrations.AddField(
            model_name='word',
            name='meanings',
            field=models.TextField(default='Ipsum Lorem'),
        ),
    ]
